"""Add character_name field to User model

Revision ID: 698406179bb9
Revises: 9adf0c408c5f
Create Date: 2025-09-23 08:56:13.292371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '698406179bb9'
down_revision = '9adf0c408c5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('character_name')

    # ### end Alembic commands ###
