"""Add Guild and GuildRelationship models

Revision ID: 9adf0c408c5f
Revises: 9716bea17dfb
Create Date: 2025-09-22 21:07:33.193191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9adf0c408c5f'
down_revision = '9716bea17dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('leadership', sa.String(length=200), nullable=True),
    sa.Column('headquarters_district_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('influence', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['headquarters_district_id'], ['district.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guild_relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_1_id', sa.Integer(), nullable=False),
    sa.Column('guild_2_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['guild_1_id'], ['guild.id'], ),
    sa.ForeignKeyConstraint(['guild_2_id'], ['guild.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_1_id', 'guild_2_id', name='unique_guild_relationship')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guild_relationship')
    op.drop_table('guild')
    # ### end Alembic commands ###
