"""Add CharacterQuickRef model for Daggerheart stats

Revision ID: f1bd76304f0e
Revises: 698406179bb9
Create Date: 2025-09-23 11:24:12.794710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1bd76304f0e'
down_revision = '698406179bb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_quick_refs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('evasion_score', sa.Integer(), nullable=True),
    sa.Column('damage_thresholds', sa.Text(), nullable=True),
    sa.Column('experiences', sa.Text(), nullable=True),
    sa.Column('class_name', sa.String(length=100), nullable=True),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_quick_refs')
    # ### end Alembic commands ###
